const numberValue = (value: unknown) => Number(value || 0);

export function mapSalesDocument(document: any) {
  return {
    id: document.id,
    code: document.code,
    orderDate: document.orderDate,
    deliveryDate: document.deliveryDate,
    dueDate: document.dueDate,
    customerId: document.customerId,
    customerCode: document.customers?.code,
    customerName: document.customers?.name,
    customerPhone: document.customers?.phone,
    customerAddress: document.customers?.address,
    customerTaxCode: document.customers?.taxCode,
    warehouseId: document.warehouseId,
    warehouseName: document.warehouses?.name,
    status: document.status === "FULFILLED" ? "POSTED" : document.status,
    note: document.note,
    rejectionReason: document.rejectionReason,
    subtotal: numberValue(document.subtotal),
    discountAmount: numberValue(document.discountAmount),
    taxAmount: numberValue(document.taxAmount),
    totalAmount: numberValue(document.totalAmount),
    paidAmount: numberValue(document.paidAmount),
    paymentStatus: document.paymentStatus,
    paymentIntent: document.paymentIntent,
    paymentMethod: document.paymentMethod,
    version: document.version,
    postedAt: document.postedAt,
    cancelledAt: document.cancelledAt,
    cancelReason: document.cancelReason,
    createdAt: document.createdAt,
    creatorName: document.users_sales_orders_createdByTousers?.fullName,
    approverName: document.users_sales_orders_approvedByTousers?.fullName,
    approvedAt: document.approvedAt,
    details: (document.sales_order_details || []).map((line: any) => ({
      id: line.id,
      packagingId: line.packagingId,
      quantity: numberValue(line.quantity),
      unitPrice: numberValue(line.unitPrice),
      discountRate: numberValue(line.discountRate),
      lineTotal: numberValue(line.lineTotal),
      unitCost: numberValue(line.unitCost),
      costAmount: numberValue(line.costAmount),
      note: line.note,
      sku: line.productpackagings?.sku,
      packagingName: line.productpackagings?.name,
      unit: line.productpackagings?.unit,
      productName: line.productpackagings?.products?.name,
    })),
    links: (document.sales_document_links_v1 || []).map((link: any) => ({
      id: String(link.id), linkType: link.linkType, linkedId: String(link.linkedId), linkedCode: link.linkedCode,
    })),
  };
}