import { Router } from "express";
import { assemblyBomInputSchema, assemblyBomListQuerySchema, assemblyBomUpdateSchema, assemblyCancelSchema, assemblyDraftSchema, assemblyPostSchema, assemblyUpdateSchema, disassemblyDraftSchema, disassemblyPostSchema, disassemblyUpdateSchema, lifecycleListQuerySchema, numericIdParamsSchema } from "@challenge/contracts";
import { asyncHandler } from "../../common/async-handler";
import { authenticateV1, requirePermission } from "../../common/authenticate";
import { validateBody, validateParams, validateQuery } from "../../common/validate";
import { assemblyController } from "./assembly.controller";
export const assemblyRouter = Router(); assemblyRouter.use(authenticateV1);
assemblyRouter.get("/boms", requirePermission("assembly.view"), validateQuery(assemblyBomListQuerySchema), asyncHandler(assemblyController.listBoms));
assemblyRouter.get("/boms/:id", requirePermission("assembly.view"), validateParams(numericIdParamsSchema), asyncHandler(assemblyController.getBom));
assemblyRouter.post("/boms", requirePermission("assembly.manage"), validateBody(assemblyBomInputSchema), asyncHandler(assemblyController.createBom));
assemblyRouter.put("/boms/:id", requirePermission("assembly.manage"), validateParams(numericIdParamsSchema), validateBody(assemblyBomUpdateSchema), asyncHandler(assemblyController.updateBom));
assemblyRouter.get("/orders", requirePermission("assembly.view"), validateQuery(lifecycleListQuerySchema), asyncHandler(assemblyController.listAssembly));
assemblyRouter.get("/orders/:id", requirePermission("assembly.view"), validateParams(numericIdParamsSchema), asyncHandler(assemblyController.getAssembly));
assemblyRouter.post("/orders", requirePermission("assembly.manage"), validateBody(assemblyDraftSchema), asyncHandler(assemblyController.createAssembly));
assemblyRouter.put("/orders/:id", requirePermission("assembly.manage"), validateParams(numericIdParamsSchema), validateBody(assemblyUpdateSchema), asyncHandler(assemblyController.updateAssembly));
assemblyRouter.post("/orders/:id/post", requirePermission("assembly.post"), validateParams(numericIdParamsSchema), validateBody(assemblyPostSchema), asyncHandler(assemblyController.postAssembly));
assemblyRouter.post("/orders/:id/cancel", requirePermission("assembly.cancel"), validateParams(numericIdParamsSchema), validateBody(assemblyCancelSchema), asyncHandler(assemblyController.cancelAssembly));
assemblyRouter.get("/disassembly-orders", requirePermission("assembly.view"), validateQuery(lifecycleListQuerySchema), asyncHandler(assemblyController.listDisassembly));
assemblyRouter.get("/disassembly-orders/:id", requirePermission("assembly.view"), validateParams(numericIdParamsSchema), asyncHandler(assemblyController.getDisassembly));
assemblyRouter.post("/disassembly-orders", requirePermission("assembly.manage"), validateBody(disassemblyDraftSchema), asyncHandler(assemblyController.createDisassembly));
assemblyRouter.put("/disassembly-orders/:id", requirePermission("assembly.manage"), validateParams(numericIdParamsSchema), validateBody(disassemblyUpdateSchema), asyncHandler(assemblyController.updateDisassembly));
assemblyRouter.post("/disassembly-orders/:id/post", requirePermission("assembly.post"), validateParams(numericIdParamsSchema), validateBody(disassemblyPostSchema), asyncHandler(assemblyController.postDisassembly));
assemblyRouter.post("/disassembly-orders/:id/cancel", requirePermission("assembly.cancel"), validateParams(numericIdParamsSchema), validateBody(assemblyCancelSchema), asyncHandler(assemblyController.cancelDisassembly));