import React, { useEffect, useState } from "react";
import { ArrowDownCircle, ArrowUpCircle, Boxes, CircleDollarSign, HandCoins, Scale, TrendingUp, WalletCards } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import toast from "react-hot-toast";
import { formatNumber } from "../lib/utils";

type Data={revenue:number;expense:number;profit:number;receivables:number;payables:number;inventoryValue:number;monthly:Array<{monthKey:string;revenue:number;expense:number}>;customerDebts:Array<{id:number;code:string;name:string;debt:number}>;lowStock:Array<{id:number;sku:string;productName:string;packagingName:string;stock:number;minStock:number}>};
const initial:Data={revenue:0,expense:0,profit:0,receivables:0,payables:0,inventoryValue:0,monthly:[],customerDebts:[],lowStock:[]};
export default function FinancialDashboard(){
 const [data,setData]=useState<Data>(initial),[loading,setLoading]=useState(true);
 useEffect(()=>{fetch("/api/dashboard/financial",{headers:{Authorization:`Bearer ${localStorage.getItem("token")}`}}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d)}).catch(e=>toast.error(e.message)).finally(()=>setLoading(false))},[]);
 const cards=[['Doanh thu',data.revenue,ArrowUpCircle,'text-emerald-600'],['Chi phí',data.expense,ArrowDownCircle,'text-red-500'],['Lợi nhuận tạm tính',data.profit,TrendingUp,data.profit>=0?'text-blue-600':'text-red-600'],['Công nợ phải thu',data.receivables,HandCoins,'text-amber-600'],['Công nợ phải trả',data.payables,WalletCards,'text-violet-600'],['Giá trị tồn kho',data.inventoryValue,Boxes,'text-cyan-600']] as const;
 return <div className="erp-page"><div className="erp-page-header"><div><h1>Tổng quan tài chính</h1><p>Doanh thu, chi phí, công nợ và tồn kho theo dữ liệu vận hành</p></div></div>{loading?<div className="erp-card p-10 text-center">Đang tổng hợp dữ liệu...</div>:<><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{cards.map(([label,value,Icon,color])=><div className="erp-stat" key={label}><Icon className={color}/><div><span>{label}</span><strong>{formatNumber(value)} ₫</strong></div></div>)}</div><div className="grid gap-4 xl:grid-cols-3"><div className="erp-card p-5 xl:col-span-2"><h2 className="mb-5 font-bold">Doanh thu và chi phí 6 tháng gần nhất</h2><div className="h-80"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.monthly}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="monthKey"/><YAxis tickFormatter={v=>`${Math.round(v/1000000)}tr`}/><Tooltip formatter={(v:any)=>`${formatNumber(Number(v))} ₫`}/><Legend/><Bar dataKey="revenue" name="Doanh thu" fill="#089740" radius={[4,4,0,0]}/><Bar dataKey="expense" name="Chi phí" fill="#ef4444" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></div><div className="erp-card p-5"><h2 className="mb-4 flex items-center gap-2 font-bold"><CircleDollarSign size={18}/> Công nợ khách hàng lớn</h2><div className="space-y-3">{data.customerDebts.length?data.customerDebts.map(c=><div key={c.id} className="border-b pb-3"><div className="flex justify-between gap-2"><b>{c.name}</b><b className="text-amber-700">{formatNumber(c.debt)} ₫</b></div><small className="text-slate-400">{c.code}</small></div>):<p className="text-sm text-slate-400">Không có công nợ phải thu.</p>}</div></div></div><div className="erp-card overflow-hidden"><div className="p-4"><h2 className="flex items-center gap-2 font-bold"><Scale size={18}/> Cảnh báo tồn kho</h2></div><table className="erp-table"><thead><tr><th>Mã hàng</th><th>Hàng hóa / Quy cách</th><th className="text-right">Tồn hiện tại</th><th className="text-right">Tồn tối thiểu</th><th>Trạng thái</th></tr></thead><tbody>{data.lowStock.map(x=><tr key={x.id}><td>{x.sku}</td><td>{x.productName} - {x.packagingName}</td><td className="text-right font-bold">{formatNumber(Number(x.stock||0))}</td><td className="text-right">{formatNumber(Number(x.minStock||0))}</td><td><span className={`erp-badge ${Number(x.stock)<=0?'bg-red-100 text-red-700':'bg-amber-100 text-amber-700'}`}>{Number(x.stock)<=0?'Hết hàng':'Sắp hết'}</span></td></tr>)}</tbody></table></div></>}</div>
}