import React, { useEffect, useMemo, useState } from "react";
import { Banknote, Copy, Eye, Plus, Search, ShoppingBag, X } from "lucide-react";
import toast from "react-hot-toast";
import { Product, PurchaseDocument, PurchaseDocumentDetail, PurchaseDocumentType, Supplier, Warehouse } from "../types";
import { formatDate, formatNumber } from "../lib/utils";

const auth = (json=false) => ({ Authorization:`Bearer ${localStorage.getItem("token")}`, ...(json?{"Content-Type":"application/json"}:{}) });
const today = () => new Date().toISOString().slice(0,10);
const emptyLine = (): PurchaseDocumentDetail => ({ packagingId:0, warehouseId:0, quantity:1, unitPrice:0, taxRate:8, note:"" });
const paymentLabel = { UNPAID:"Chưa thanh toán", PARTIAL:"Thanh toán một phần", PAID:"Đã thanh toán" };

export default function Purchases(){
  const [documents,setDocuments]=useState<PurchaseDocument[]>([]), [suppliers,setSuppliers]=useState<Supplier[]>([]), [warehouses,setWarehouses]=useState<Warehouse[]>([]), [products,setProducts]=useState<Product[]>([]);
  const [loading,setLoading]=useState(true), [saving,setSaving]=useState(false), [open,setOpen]=useState(false), [selected,setSelected]=useState<PurchaseDocument|null>(null), [search,setSearch]=useState("");
  const [form,setForm]=useState({ documentDate:today(), dueDate:"", type:"DOMESTIC_INVENTORY" as PurchaseDocumentType, paymentStatus:"UNPAID", paymentMethod:"CASH", invoiceOption:"WITH_INVOICE", supplierId:0, deliveryPerson:"", buyerName:"", description:"", purchaseCost:0 });
  const [details,setDetails]=useState<PurchaseDocumentDetail[]>([emptyLine()]);
  const request=async(url:string,options?:RequestInit)=>{const r=await fetch(url,{...options,headers:auth(!!options?.body)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Có lỗi xảy ra");return d};
  const load=async()=>{setLoading(true);try{const [ds,ss,ws,ps]=await Promise.all([request("/api/purchase-documents"),request("/api/suppliers"),request("/api/warehouses"),request("/api/products")]);setDocuments(ds);setSuppliers(ss);setWarehouses(ws);setProducts(ps);setForm(f=>({...f,supplierId:f.supplierId||ss[0]?.id||0}));}catch(e:any){toast.error(e.message)}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const options=useMemo(()=>products.flatMap(p=>(p.packagings||[]).map(pk=>({...pk,productName:p.name,category:(p as any).category}))),[products]);
  const filtered=documents.filter(d=>`${d.code} ${d.supplierName}`.toLowerCase().includes(search.toLowerCase()));
  const goods=details.reduce((s,d)=>s+d.quantity*d.unitPrice,0), tax=details.reduce((s,d)=>s+d.quantity*d.unitPrice*d.taxRate/100,0), total=goods+tax+Number(form.purchaseCost||0);
  const update=(i:number,p:Partial<PurchaseDocumentDetail>)=>setDetails(rs=>rs.map((r,x)=>x===i?{...r,...p}:r));
  const reset=(source?:PurchaseDocument)=>{if(source){setForm({documentDate:today(),dueDate:source.dueDate||"",type:source.type,paymentStatus:"UNPAID",paymentMethod:"CASH",invoiceOption:source.invoiceOption,supplierId:source.supplierId,deliveryPerson:source.deliveryPerson||"",buyerName:source.buyerName||"",description:`Nhân bản từ ${source.code}`,purchaseCost:Number(source.purchaseCost)});setDetails(source.details.map(d=>({packagingId:d.packagingId,warehouseId:d.warehouseId||0,quantity:Number(d.quantity),unitPrice:Number(d.unitPrice),taxRate:Number(d.taxRate),note:d.note||""})));}else{setDetails([emptyLine()]);setForm(f=>({...f,documentDate:today(),dueDate:"",deliveryPerson:"",description:"",purchaseCost:0}));}setOpen(true)};
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);try{await request("/api/purchase-documents",{method:"POST",body:JSON.stringify({...form,details})});toast.success("Đã lưu chứng từ và cập nhật kho");setOpen(false);await load()}catch(e:any){toast.error(e.message)}finally{setSaving(false)}};
  const pay=async(d:PurchaseDocument)=>{const remaining=Number(d.totalAmount)-Number(d.paidAmount);const input=window.prompt(`Công nợ còn lại ${formatNumber(remaining)} ₫. Nhập số tiền thanh toán:`,String(remaining));if(!input)return;try{await request(`/api/purchase-documents/${d.id}/payments`,{method:"POST",body:JSON.stringify({amount:Number(input),paymentDate:today(),method:"BANK"})});toast.success("Đã ghi nhận thanh toán");await load()}catch(e:any){toast.error(e.message)}};
  return <div className="erp-page">
    <div className="erp-page-header"><div><h1>Mua hàng</h1><p>Chứng từ mua hàng, nhập kho và công nợ phải trả</p></div><button className="erp-btn erp-btn-primary" onClick={()=>reset()} disabled={!suppliers.length}><Plus size={17}/> Thêm chứng từ</button></div>
    {!suppliers.length&&!loading&&<div className="rounded border border-amber-200 bg-amber-50 p-4 text-amber-800">Cần tạo nhà cung cấp trước khi lập chứng từ mua hàng.</div>}
    <div className="grid gap-4 md:grid-cols-3"><div className="erp-stat"><ShoppingBag/><div><span>Tổng chứng từ</span><strong>{documents.length}</strong></div></div><div className="erp-stat"><Banknote/><div><span>Tổng mua hàng</span><strong>{formatNumber(documents.reduce((s,d)=>s+Number(d.totalAmount),0))} ₫</strong></div></div><div className="erp-stat"><Banknote/><div><span>Công nợ phải trả</span><strong>{formatNumber(documents.reduce((s,d)=>s+Number(d.totalAmount)-Number(d.paidAmount),0))} ₫</strong></div></div></div>
    <div className="erp-card overflow-hidden"><div className="erp-toolbar"><div className="erp-search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tìm số chứng từ, nhà cung cấp..."/></div></div><div className="overflow-x-auto"><table className="erp-table"><thead><tr><th>Số chứng từ / Ngày</th><th>Nhà cung cấp</th><th className="text-right">Tổng tiền hàng</th><th className="text-right">Giá trị nhập kho</th><th>Thanh toán</th><th>Loại chứng từ</th><th></th></tr></thead><tbody>{loading?<tr><td colSpan={7} className="text-center">Đang tải...</td></tr>:filtered.map(d=><tr key={d.id}><td><button className="font-semibold text-emerald-700" onClick={()=>setSelected(d)}>{d.code}</button><small>{formatDate(d.documentDate)}</small></td><td><b>{d.supplierName}</b><small>{d.supplierCode}</small></td><td className="text-right font-semibold">{formatNumber(d.goodsAmount)} ₫</td><td className="text-right">{formatNumber(d.inventoryValue)} ₫</td><td><span className={`erp-badge ${d.paymentStatus==='PAID'?'bg-emerald-100 text-emerald-700':d.paymentStatus==='PARTIAL'?'bg-blue-100 text-blue-700':'bg-amber-100 text-amber-700'}`}>{paymentLabel[d.paymentStatus]}</span><small>Còn: {formatNumber(d.totalAmount-d.paidAmount)} ₫</small></td><td>{d.type==='DOMESTIC_INVENTORY'?'Mua nhập kho':'Không qua kho'}</td><td><div className="flex justify-end"><button className="erp-icon-btn" title="Xem" onClick={()=>setSelected(d)}><Eye size={16}/></button><button className="erp-icon-btn" title="Nhân bản" onClick={()=>reset(d)}><Copy size={16}/></button>{d.paymentStatus!=='PAID'&&<button className="erp-icon-btn text-emerald-700" title="Thanh toán" onClick={()=>pay(d)}><Banknote size={16}/></button>}</div></td></tr>)}</tbody></table></div></div>
    {open&&<div className="erp-modal-backdrop"><div className="erp-modal max-w-6xl"><div className="erp-modal-header"><div><h2>Thêm chứng từ mua hàng</h2><p>Lưu chứng từ sẽ tự động tạo phiếu nhập theo từng kho</p></div><button onClick={()=>setOpen(false)}><X/></button></div><form onSubmit={submit}><div className="erp-modal-body space-y-5"><div className="grid gap-4 md:grid-cols-4"><label>Loại chứng từ<select value={form.type} onChange={e=>setForm({...form,type:e.target.value as PurchaseDocumentType})}><option value="DOMESTIC_INVENTORY">Mua trong nước nhập kho</option><option value="DOMESTIC_NO_INVENTORY">Mua không qua kho</option></select></label><label>Nhà cung cấp<select required value={form.supplierId} onChange={e=>setForm({...form,supplierId:+e.target.value})}>{suppliers.map(s=><option key={s.id} value={s.id}>{s.code} - {s.name}</option>)}</select></label><label>Ngày chứng từ<input type="date" required value={form.documentDate} onChange={e=>setForm({...form,documentDate:e.target.value})}/></label><label>Hạn thanh toán<input type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label><label>Trạng thái thanh toán<select value={form.paymentStatus} onChange={e=>setForm({...form,paymentStatus:e.target.value})}><option value="UNPAID">Chưa thanh toán</option><option value="PAID">Thanh toán ngay</option></select></label>{form.paymentStatus==='PAID'&&<label>Phương thức<select value={form.paymentMethod} onChange={e=>setForm({...form,paymentMethod:e.target.value})}><option value="CASH">Tiền mặt</option><option value="BANK">Chuyển khoản</option></select></label>}<label>Hóa đơn<select value={form.invoiceOption} onChange={e=>setForm({...form,invoiceOption:e.target.value})}><option value="WITH_INVOICE">Nhận kèm hóa đơn GTGT</option><option value="NO_INVOICE">Không có hóa đơn</option></select></label><label>Người giao hàng<input value={form.deliveryPerson} onChange={e=>setForm({...form,deliveryPerson:e.target.value})}/></label></div>
    <div className="overflow-x-auto border rounded"><table className="erp-table"><thead><tr><th>Hàng hóa / Quy cách</th>{form.type==='DOMESTIC_INVENTORY'&&<th>Kho</th>}<th>SL</th><th>Đơn giá</th><th>Thuế %</th><th className="text-right">Thành tiền</th><th></th></tr></thead><tbody>{details.map((d,i)=><tr key={i}><td><select required value={d.packagingId} onChange={e=>update(i,{packagingId:+e.target.value})}><option value={0}>Chọn hàng hóa</option>{options.map(p=><option key={p.id} value={p.id}>{p.productName} - {p.name} ({p.sku})</option>)}</select></td>{form.type==='DOMESTIC_INVENTORY'&&<td><select required value={d.warehouseId||0} onChange={e=>update(i,{warehouseId:+e.target.value})}><option value={0}>Chọn kho</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></td>}<td><input className="w-24" type="number" min="0.01" step="any" value={d.quantity} onChange={e=>update(i,{quantity:+e.target.value})}/></td><td><input className="w-32" type="number" min="0" step="any" value={d.unitPrice} onChange={e=>update(i,{unitPrice:+e.target.value})}/></td><td><input className="w-20" type="number" min="0" value={d.taxRate} onChange={e=>update(i,{taxRate:+e.target.value})}/></td><td className="text-right font-semibold">{formatNumber(d.quantity*d.unitPrice*(1+d.taxRate/100))}</td><td><button type="button" className="erp-icon-btn text-red-500" disabled={details.length===1} onClick={()=>setDetails(r=>r.filter((_,x)=>x!==i))}><X size={15}/></button></td></tr>)}</tbody></table></div><div className="flex gap-2"><button type="button" className="erp-btn" onClick={()=>setDetails(r=>[...r,emptyLine()])}><Plus size={15}/> Thêm dòng sản phẩm</button><button type="button" className="erp-btn" onClick={()=>setDetails([emptyLine()])}>Xóa hết dòng</button></div>
    <div className="grid gap-4 md:grid-cols-2"><label>Diễn giải mua hàng<textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="ml-auto w-full max-w-sm space-y-2"><div className="flex justify-between"><span>Tổng tiền hàng</span><b>{formatNumber(goods)} ₫</b></div><div className="flex justify-between"><span>Thuế</span><b>{formatNumber(tax)} ₫</b></div><div className="flex items-center justify-between"><span>Chi phí mua hàng</span><input className="w-32" type="number" min="0" value={form.purchaseCost} onChange={e=>setForm({...form,purchaseCost:+e.target.value})}/></div><div className="flex justify-between border-t pt-2 text-lg text-emerald-700"><b>Tổng thanh toán</b><b>{formatNumber(total)} ₫</b></div></div></div></div><div className="erp-modal-footer"><button type="button" className="erp-btn" onClick={()=>setOpen(false)}>Hủy</button><button disabled={saving} className="erp-btn erp-btn-primary">{saving?'Đang lưu...':'Lưu và đóng'}</button></div></form></div></div>}
    {selected&&<div className="erp-modal-backdrop"><div className="erp-modal max-w-4xl"><div className="erp-modal-header"><div><h2>{selected.code}</h2><p>{selected.supplierName} · {formatDate(selected.documentDate)}</p></div><button onClick={()=>setSelected(null)}><X/></button></div><div className="erp-modal-body space-y-4"><div className="grid gap-3 md:grid-cols-3"><div><small>Người giao</small><b className="block">{selected.deliveryPerson||"-"}</b></div><div><small>Nhân viên mua hàng</small><b className="block">{selected.buyerName||selected.creatorName}</b></div><div><small>Phiếu nhập liên kết</small><b className="block">{selected.inventoryLinks?.map(x=>x.inventoryCode).join(", ")||"Không qua kho"}</b></div></div><table className="erp-table"><thead><tr><th>Hàng hóa</th><th>Kho</th><th>SL</th><th className="text-right">Đơn giá</th><th className="text-right">Tiền + thuế</th></tr></thead><tbody>{selected.details.map(d=><tr key={d.id}><td>{d.productName} - {d.packagingName}<small>{d.sku}</small></td><td>{d.warehouseName||"-"}</td><td>{formatNumber(d.quantity)} {d.unit}</td><td className="text-right">{formatNumber(d.unitPrice)}</td><td className="text-right font-semibold">{formatNumber(Number(d.lineAmount)+Number(d.taxAmount))} ₫</td></tr>)}</tbody></table><div className="text-right text-xl font-bold text-emerald-700">Tổng thanh toán: {formatNumber(selected.totalAmount)} ₫</div></div></div></div>}
  </div>
}