const numberValue = (value: unknown) => Number(value || 0);

export function mapPurchaseDocument(document: any) {
  return {
    id: document.id,
    code: document.code,
    documentDate: document.documentDate,
    dueDate: document.dueDate,
    type: document.type,
    documentStatus: document.documentStatus,
    paymentStatus: document.paymentStatus,
    paymentIntent: document.paymentIntent,
    paymentMethod: document.paymentMethod,
    invoiceOption: document.invoiceOption,
    supplierId: document.supplierId,
    supplierCode: document.suppliers?.code,
    supplierName: document.suppliers?.name,
    deliveryPerson: document.deliveryPerson,
    buyerName: document.buyerName,
    description: document.description,
    goodsAmount: numberValue(document.goodsAmount),
    taxAmount: numberValue(document.taxAmount),
    purchaseCost: numberValue(document.purchaseCost),
    totalAmount: numberValue(document.totalAmount),
    inventoryValue: numberValue(document.inventoryValue),
    paidAmount: numberValue(document.paidAmount),
    version: document.version,
    postedAt: document.postedAt,
    cancelledAt: document.cancelledAt,
    cancelReason: document.cancelReason,
    creatorName: document.users?.fullName,
    details: (document.purchase_document_details || []).map((line: any) => ({
      id: line.id,
      packagingId: line.packagingId,
      warehouseId: line.warehouseId,
      quantity: numberValue(line.quantity),
      unitPrice: numberValue(line.unitPrice),
      taxRate: numberValue(line.taxRate),
      lineAmount: numberValue(line.lineAmount),
      taxAmount: numberValue(line.taxAmount),
      note: line.note,
      sku: line.productpackagings?.sku,
      packagingName: line.productpackagings?.name,
      unit: line.productpackagings?.unit,
      productName: line.productpackagings?.products?.name,
      warehouseName: line.warehouses?.name,
    })),
    links: (document.purchase_document_links_v1 || []).map((link: any) => ({
      id: String(link.id), linkType: link.linkType, linkedId: String(link.linkedId), linkedCode: link.linkedCode,
    })),
  };
}